// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDFM6QTa5bJsGWEvM7lZtnyMvyJ7zhNPA',
    appId: '1:1053497533240:web:61adf0c55204d73f9617cd',
    messagingSenderId: '1053497533240',
    projectId: 'mathspoint',
    authDomain: 'mathspoint.firebaseapp.com',
    storageBucket: 'mathspoint.firebasestorage.app',
    measurementId: 'G-1JLF07ZNM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVukSWdaM8g1013gpIQ9XNC084JIa1G0c',
    appId: '1:1053497533240:android:09b1a3316da16b069617cd',
    messagingSenderId: '1053497533240',
    projectId: 'mathspoint',
    storageBucket: 'mathspoint.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYOOhgr2d1mnyDCdrKq61xJraBwbGSe2I',
    appId: '1:1053497533240:ios:2e9dee02d6eff5fc9617cd',
    messagingSenderId: '1053497533240',
    projectId: 'mathspoint',
    storageBucket: 'mathspoint.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYOOhgr2d1mnyDCdrKq61xJraBwbGSe2I',
    appId: '1:1053497533240:ios:2e9dee02d6eff5fc9617cd',
    messagingSenderId: '1053497533240',
    projectId: 'mathspoint',
    storageBucket: 'mathspoint.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDFM6QTa5bJsGWEvM7lZtnyMvyJ7zhNPA',
    appId: '1:1053497533240:web:ed70799b08088eae9617cd',
    messagingSenderId: '1053497533240',
    projectId: 'mathspoint',
    authDomain: 'mathspoint.firebaseapp.com',
    storageBucket: 'mathspoint.firebasestorage.app',
    measurementId: 'G-BPW1NVMWXX',
  );
}
